project:
  type: website

website:
  title: "ShivamPR21"
  favicon: /logo.png
  site-url: https://shivampr21.github.io
  page-footer: "Copyright 2025, Shivam Pandey @ShivamPR21"
  back-to-top-navigation: true
  reader-mode: true
  twitter-card:
    creator: "@ShivamPR21"
    site: "@ShivamPR21"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: kernelized.qmd
        text: KERNELIZED
    right:
      - icon: twitter
        href: https://twitter.com/shivampr21
      - icon: github
        href: https://github.com/shivampr21
      - icon: linkedin
        href: https://linkedin.com/in/shivampr21
      - text: CV
        href: /Shivam_Pandey_ShivamPR21__JSR.pdf
      - text: Single Page CV
        href: /Shivam_Pandey_ShivamPR21_SP_JSR.pdf

format:
  html:
    theme: united
    css: styles.css
    toc: true
    highlight-style: github
    html-math-method: mathjax
    mermaid:
      theme: dark
    # code-fold: true
    # code-summary: "Show code"
    # code-tools: true
